services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin1234
    command: server /data --console-address ":9001"
    networks:
      - app-network
    volumes:
      - minio_data:/data

  redpanda:
    image: redpandadata/redpanda:latest
    ports:
      - "9092:9092" # Kafka broker port for clients
      - "9644:9644" # HTTP admin port
      - "8081:8081" # RPC port
      - "8082:8082" # Schema Registry port (if default listener is configured)
    command:
      - redpanda
      - start
      - --smp 1
      - --overprovisioned
      # 1. Define ONE internal listener for all traffic.
      - --kafka-addr internal://0.0.0.0:9092
      # 2. Advertise TWO ways to connect to it.
      - --advertise-kafka-addr internal://redpanda:9092,outside://localhost:9092
    volumes:
      - ./redpanda/data:/var/lib/redpanda/data # Changed from /var/lib/kafka to /var/lib/redpanda/data for clarity
    networks:
      - app-network

  redpanda-console:
    image: redpandadata/console:latest
    ports:
      - "8080:8080" # Redpanda Console port
    environment:
      KAFKA_BROKERS: "redpanda:9092" # Note: Redpanda Console uses KAFKA_BROKERS
      # Add any other specific environment variables for redpanda-console if needed.
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    environment:
      - OLLAMA_MODELS=nomic-embed-text:latest,moondream:1.8b,granite3.2-vision:2b,orca-mini:3b,gemma3:4b
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    pull_policy: always
    tty: true
    restart: unless-stopped
    networks:
      - app-network

  ingestion:
    build:
      context: ./ingestion
    ports:
      - "8000:8000"
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin1234
      MINIO_BUCKET: videos
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
    networks:
      - app-network

  storage:
    build:
      context: ./storage
    ports:
      - "8001:8001"
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin1234
      MINIO_BUCKET: videos
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      FAISS_INDEX_PATH: /app/faiss/video_index.faiss
      OLLAMA_ENDPOINT: http://ollama:11434
    volumes:
      - faiss_data:/app/faiss
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - app-network

  query_alert:
    build:
      context: ./query_alert
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin1234
      MINIO_BUCKET: videos
      OLLAMA_ENDPOINT: http://ollama:11434
      STORAGE_ENDPOINT: http://storage:8001
    networks:
      - app-network

  streamlit:
    build:
      context: ./streamlit
    ports:
      - "8501:8501"
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin1234
      MINIO_BUCKET: videos
      INGESTION_ENDPOINT: http://ingestion:8000
      STORAGE_ENDPOINT: http://storage:8001
      OLLAMA_ENDPOINT: http://ollama:11434
    networks:
      - app-network
    volumes:
      - faiss_data:/app/faiss

  audio_backend:
    build:
      context: ./audio_api/backend
      dockerfile: Dockerfile
    environment:
      - ELEVENLABS_API_KEY=sk_a12b076d3f9c4f02ef432a874ebe914fac0309d259a1fea9
    ports:
      - "8003:8000" # Expose on host port 8003, container port 8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  minio_data:
  ollama_data:
  faiss_data:
